import type { Country, Continent } from "./types";

export const CONTINENT_COLORS: Record<Continent, string> = {
  Africa: "#e8a838",
  Asia: "#e05555",
  Europe: "#5b7db1",
  "North America": "#6bba6b",
  "South America": "#c06bc0",
  Oceania: "#3dbdbd",
};

export const countries: Country[] = [
  // ── North America ──────────────────────────────────────────────
  {
    id: "usa",
    name: "United States",
    capital: "Washington, D.C.",
    continent: "North America",
    region: "Northern America",
    population: 331_900_000,
    area: 9_833_520,
    gdp: 25_460_000_000_000,
    languages: ["English"],
    currency: "USD",
    flag: "\u{1F1FA}\u{1F1F8}",
    funFacts: [
      "Has 50 states and 14 territories.",
      "The Mississippi River is the longest river system in North America.",
      "Alaska is the largest state by area, larger than Texas, California, and Montana combined.",
    ],
    lat: 39.8,
    lng: -98.6,
  },
  {
    id: "canada",
    name: "Canada",
    capital: "Ottawa",
    continent: "North America",
    region: "Northern America",
    population: 39_900_000,
    area: 9_984_670,
    gdp: 2_140_000_000_000,
    languages: ["English", "French"],
    currency: "CAD",
    flag: "\u{1F1E8}\u{1F1E6}",
    funFacts: [
      "Has the longest coastline of any country in the world.",
      "Home to 10% of the world's forests.",
      "Has more lakes than all other countries combined.",
    ],
    lat: 56.1,
    lng: -106.3,
  },
  {
    id: "mexico",
    name: "Mexico",
    capital: "Mexico City",
    continent: "North America",
    region: "Central America",
    population: 128_900_000,
    area: 1_964_375,
    gdp: 1_290_000_000_000,
    languages: ["Spanish"],
    currency: "MXN",
    flag: "\u{1F1F2}\u{1F1FD}",
    funFacts: [
      "Home to the world's smallest volcano, Cuexcomate, at just 43 feet tall.",
      "Mexico City is sinking at a rate of about 50 cm per year.",
      "Birthplace of chocolate, chili peppers, and corn.",
    ],
    lat: 23.6,
    lng: -102.6,
  },
  {
    id: "cuba",
    name: "Cuba",
    capital: "Havana",
    continent: "North America",
    region: "Caribbean",
    population: 11_300_000,
    area: 109_884,
    gdp: 107_000_000_000,
    languages: ["Spanish"],
    currency: "CUP",
    flag: "\u{1F1E8}\u{1F1FA}",
    funFacts: [
      "The largest island in the Caribbean.",
      "Classic American cars from the 1950s still fill the streets.",
    ],
    lat: 21.5,
    lng: -80.0,
  },

  // ── South America ──────────────────────────────────────────────
  {
    id: "brazil",
    name: "Brazil",
    capital: "Brasilia",
    continent: "South America",
    region: "South America",
    population: 214_300_000,
    area: 8_515_767,
    gdp: 1_920_000_000_000,
    languages: ["Portuguese"],
    currency: "BRL",
    flag: "\u{1F1E7}\u{1F1F7}",
    funFacts: [
      "Contains about 60% of the Amazon Rainforest.",
      "Has won the FIFA World Cup a record 5 times.",
      "Home to the world's largest carnival in Rio de Janeiro.",
    ],
    lat: -14.2,
    lng: -51.9,
  },
  {
    id: "argentina",
    name: "Argentina",
    capital: "Buenos Aires",
    continent: "South America",
    region: "South America",
    population: 45_800_000,
    area: 2_780_400,
    gdp: 632_000_000_000,
    languages: ["Spanish"],
    currency: "ARS",
    flag: "\u{1F1E6}\u{1F1F7}",
    funFacts: [
      "Home to the southernmost city in the world, Ushuaia.",
      "Tango dance originated in Buenos Aires.",
      "Has the widest avenue in the world, Avenida 9 de Julio.",
    ],
    lat: -38.4,
    lng: -63.6,
  },
  {
    id: "colombia",
    name: "Colombia",
    capital: "Bogota",
    continent: "South America",
    region: "South America",
    population: 51_900_000,
    area: 1_141_748,
    gdp: 314_000_000_000,
    languages: ["Spanish"],
    currency: "COP",
    flag: "\u{1F1E8}\u{1F1F4}",
    funFacts: [
      "The only South American country with coastlines on both the Pacific and Atlantic.",
      "Produces about 12% of the world's coffee.",
      "Home to the colorful Cano Cristales, called the 'River of Five Colors'.",
    ],
    lat: 4.6,
    lng: -74.1,
  },
  {
    id: "chile",
    name: "Chile",
    capital: "Santiago",
    continent: "South America",
    region: "South America",
    population: 19_500_000,
    area: 756_102,
    gdp: 301_000_000_000,
    languages: ["Spanish"],
    currency: "CLP",
    flag: "\u{1F1E8}\u{1F1F1}",
    funFacts: [
      "The world's longest north-south country, stretching over 4,300 km.",
      "Home to the Atacama Desert, the driest place on Earth.",
    ],
    lat: -35.7,
    lng: -71.5,
  },
  {
    id: "peru",
    name: "Peru",
    capital: "Lima",
    continent: "South America",
    region: "South America",
    population: 33_700_000,
    area: 1_285_216,
    gdp: 223_000_000_000,
    languages: ["Spanish", "Quechua", "Aymara"],
    currency: "PEN",
    flag: "\u{1F1F5}\u{1F1EA}",
    funFacts: [
      "Home to Machu Picchu, one of the New Seven Wonders of the World.",
      "The Amazon River originates in the Peruvian Andes.",
    ],
    lat: -9.2,
    lng: -75.0,
  },

  // ── Europe ─────────────────────────────────────────────────────
  {
    id: "uk",
    name: "United Kingdom",
    capital: "London",
    continent: "Europe",
    region: "Northern Europe",
    population: 67_900_000,
    area: 243_610,
    gdp: 3_070_000_000_000,
    languages: ["English"],
    currency: "GBP",
    flag: "\u{1F1EC}\u{1F1E7}",
    funFacts: [
      "The London Underground is the oldest metro system in the world (1863).",
      "Has no written constitution.",
      "Invented football, cricket, rugby, and golf.",
    ],
    lat: 55.4,
    lng: -3.4,
  },
  {
    id: "france",
    name: "France",
    capital: "Paris",
    continent: "Europe",
    region: "Western Europe",
    population: 67_800_000,
    area: 643_801,
    gdp: 2_780_000_000_000,
    languages: ["French"],
    currency: "EUR",
    flag: "\u{1F1EB}\u{1F1F7}",
    funFacts: [
      "Most visited country in the world with ~90 million tourists per year.",
      "The Louvre is the world's largest and most visited art museum.",
      "Has 1,500 types of cheese.",
    ],
    lat: 46.2,
    lng: 2.2,
  },
  {
    id: "germany",
    name: "Germany",
    capital: "Berlin",
    continent: "Europe",
    region: "Western Europe",
    population: 83_200_000,
    area: 357_022,
    gdp: 4_260_000_000_000,
    languages: ["German"],
    currency: "EUR",
    flag: "\u{1F1E9}\u{1F1EA}",
    funFacts: [
      "Has over 1,500 different beers brewed in 1,300 breweries.",
      "The autobahn has sections with no speed limit.",
      "Home to the world's narrowest street, Spreuerhofstrasse (31 cm wide).",
    ],
    lat: 51.2,
    lng: 10.4,
  },
  {
    id: "spain",
    name: "Spain",
    capital: "Madrid",
    continent: "Europe",
    region: "Southern Europe",
    population: 47_400_000,
    area: 505_990,
    gdp: 1_400_000_000_000,
    languages: ["Spanish"],
    currency: "EUR",
    flag: "\u{1F1EA}\u{1F1F8}",
    funFacts: [
      "Has the second-highest number of UNESCO World Heritage Sites.",
      "La Tomatina festival involves throwing 150,000 tomatoes.",
      "Spanish is the official language of 20 countries.",
    ],
    lat: 40.5,
    lng: -3.7,
  },
  {
    id: "italy",
    name: "Italy",
    capital: "Rome",
    continent: "Europe",
    region: "Southern Europe",
    population: 59_600_000,
    area: 301_340,
    gdp: 2_010_000_000_000,
    languages: ["Italian"],
    currency: "EUR",
    flag: "\u{1F1EE}\u{1F1F9}",
    funFacts: [
      "Has more UNESCO World Heritage Sites than any other country.",
      "Home to the world's oldest university, the University of Bologna (1088).",
      "The country has a free wine fountain in Caldari di Ortona.",
    ],
    lat: 41.9,
    lng: 12.6,
  },
  {
    id: "russia",
    name: "Russia",
    capital: "Moscow",
    continent: "Europe",
    region: "Eastern Europe",
    population: 144_100_000,
    area: 17_098_242,
    gdp: 1_780_000_000_000,
    languages: ["Russian"],
    currency: "RUB",
    flag: "\u{1F1F7}\u{1F1FA}",
    funFacts: [
      "The largest country in the world, spanning 11 time zones.",
      "Lake Baikal contains about 20% of the world's unfrozen freshwater.",
      "The Moscow Metro is famous for its ornate station architecture.",
    ],
    lat: 61.5,
    lng: 105.3,
  },
  {
    id: "poland",
    name: "Poland",
    capital: "Warsaw",
    continent: "Europe",
    region: "Eastern Europe",
    population: 37_800_000,
    area: 312_696,
    gdp: 688_000_000_000,
    languages: ["Polish"],
    currency: "PLN",
    flag: "\u{1F1F5}\u{1F1F1}",
    funFacts: [
      "Home to the Wieliczka Salt Mine, a UNESCO site with underground chapels.",
      "Marie Curie was born in Warsaw.",
    ],
    lat: 51.9,
    lng: 19.1,
  },
  {
    id: "ukraine",
    name: "Ukraine",
    capital: "Kyiv",
    continent: "Europe",
    region: "Eastern Europe",
    population: 44_100_000,
    area: 603_500,
    gdp: 160_000_000_000,
    languages: ["Ukrainian"],
    currency: "UAH",
    flag: "\u{1F1FA}\u{1F1E6}",
    funFacts: [
      "Has the deepest metro station in the world, Arsenalna in Kyiv (105.5 m).",
      "One of the world's largest grain exporters.",
    ],
    lat: 48.4,
    lng: 31.2,
  },
  {
    id: "sweden",
    name: "Sweden",
    capital: "Stockholm",
    continent: "Europe",
    region: "Northern Europe",
    population: 10_400_000,
    area: 450_295,
    gdp: 586_000_000_000,
    languages: ["Swedish"],
    currency: "SEK",
    flag: "\u{1F1F8}\u{1F1EA}",
    funFacts: [
      "Home to the Nobel Prizes, awarded annually since 1901.",
      "Has the right of public access (Allemansratten) to roam freely in nature.",
    ],
    lat: 60.1,
    lng: 18.6,
  },
  {
    id: "norway",
    name: "Norway",
    capital: "Oslo",
    continent: "Europe",
    region: "Northern Europe",
    population: 5_400_000,
    area: 323_802,
    gdp: 579_000_000_000,
    languages: ["Norwegian"],
    currency: "NOK",
    flag: "\u{1F1F3}\u{1F1F4}",
    funFacts: [
      "Has the world's longest road tunnel, the Laerdal Tunnel (24.5 km).",
      "The country's sovereign wealth fund is worth over $1.5 trillion.",
    ],
    lat: 60.5,
    lng: 8.5,
  },
  {
    id: "netherlands",
    name: "Netherlands",
    capital: "Amsterdam",
    continent: "Europe",
    region: "Western Europe",
    population: 17_500_000,
    area: 41_543,
    gdp: 1_010_000_000_000,
    languages: ["Dutch"],
    currency: "EUR",
    flag: "\u{1F1F3}\u{1F1F1}",
    funFacts: [
      "About one-third of the country lies below sea level.",
      "Has more bicycles than people.",
    ],
    lat: 52.1,
    lng: 5.3,
  },
  {
    id: "switzerland",
    name: "Switzerland",
    capital: "Bern",
    continent: "Europe",
    region: "Western Europe",
    population: 8_800_000,
    area: 41_285,
    gdp: 808_000_000_000,
    languages: ["German", "French", "Italian", "Romansh"],
    currency: "CHF",
    flag: "\u{1F1E8}\u{1F1ED}",
    funFacts: [
      "Has enough nuclear bunker space for its entire population.",
      "The country has not been in a state of war since 1815.",
    ],
    lat: 46.8,
    lng: 8.2,
  },
  {
    id: "greece",
    name: "Greece",
    capital: "Athens",
    continent: "Europe",
    region: "Southern Europe",
    population: 10_700_000,
    area: 131_957,
    gdp: 219_000_000_000,
    languages: ["Greek"],
    currency: "EUR",
    flag: "\u{1F1EC}\u{1F1F7}",
    funFacts: [
      "Birthplace of democracy, the Olympic Games, and Western philosophy.",
      "Has over 6,000 islands, only 227 of which are inhabited.",
    ],
    lat: 39.1,
    lng: 21.8,
  },
  {
    id: "portugal",
    name: "Portugal",
    capital: "Lisbon",
    continent: "Europe",
    region: "Southern Europe",
    population: 10_300_000,
    area: 92_212,
    gdp: 253_000_000_000,
    languages: ["Portuguese"],
    currency: "EUR",
    flag: "\u{1F1F5}\u{1F1F9}",
    funFacts: [
      "One of the oldest nations in Europe, with borders largely unchanged since 1297.",
      "Lisbon is older than Rome by four centuries.",
    ],
    lat: 39.4,
    lng: -8.2,
  },
  {
    id: "turkey",
    name: "Turkey",
    capital: "Ankara",
    continent: "Europe",
    region: "Western Asia",
    population: 84_800_000,
    area: 783_562,
    gdp: 906_000_000_000,
    languages: ["Turkish"],
    currency: "TRY",
    flag: "\u{1F1F9}\u{1F1F7}",
    funFacts: [
      "Straddles two continents, Europe and Asia.",
      "Istanbul was the capital of three empires: Roman, Byzantine, and Ottoman.",
      "Introduced coffee to Europe.",
    ],
    lat: 38.9,
    lng: 35.2,
  },

  // ── Africa ─────────────────────────────────────────────────────
  {
    id: "egypt",
    name: "Egypt",
    capital: "Cairo",
    continent: "Africa",
    region: "Northern Africa",
    population: 104_300_000,
    area: 1_002_450,
    gdp: 404_000_000_000,
    languages: ["Arabic"],
    currency: "EGP",
    flag: "\u{1F1EA}\u{1F1EC}",
    funFacts: [
      "The Great Pyramid of Giza is the oldest of the Seven Wonders of the Ancient World.",
      "The Nile is the longest river in the world at 6,650 km.",
      "Ancient Egyptians invented toothpaste, paper, and door locks.",
    ],
    lat: 26.8,
    lng: 30.8,
  },
  {
    id: "south-africa",
    name: "South Africa",
    capital: "Pretoria",
    continent: "Africa",
    region: "Southern Africa",
    population: 60_000_000,
    area: 1_221_037,
    gdp: 405_000_000_000,
    languages: ["Zulu", "Xhosa", "Afrikaans", "English"],
    currency: "ZAR",
    flag: "\u{1F1FF}\u{1F1E6}",
    funFacts: [
      "Has three capital cities: Pretoria, Cape Town, and Bloemfontein.",
      "Home to the world's largest individually timed cycle race.",
      "Has 11 official languages.",
    ],
    lat: -30.6,
    lng: 22.9,
  },
  {
    id: "nigeria",
    name: "Nigeria",
    capital: "Abuja",
    continent: "Africa",
    region: "Western Africa",
    population: 218_500_000,
    area: 923_768,
    gdp: 477_000_000_000,
    languages: ["English"],
    currency: "NGN",
    flag: "\u{1F1F3}\u{1F1EC}",
    funFacts: [
      "Most populous country in Africa.",
      "Nollywood produces more films annually than Hollywood.",
      "Has over 500 distinct ethnic groups.",
    ],
    lat: 9.1,
    lng: 8.7,
  },
  {
    id: "kenya",
    name: "Kenya",
    capital: "Nairobi",
    continent: "Africa",
    region: "Eastern Africa",
    population: 53_800_000,
    area: 580_367,
    gdp: 113_000_000_000,
    languages: ["Swahili", "English"],
    currency: "KES",
    flag: "\u{1F1F0}\u{1F1EA}",
    funFacts: [
      "Named after Mount Kenya, the second-highest mountain in Africa.",
      "The Great Rift Valley runs through the country.",
    ],
    lat: -0.02,
    lng: 37.9,
  },
  {
    id: "ethiopia",
    name: "Ethiopia",
    capital: "Addis Ababa",
    continent: "Africa",
    region: "Eastern Africa",
    population: 120_300_000,
    area: 1_104_300,
    gdp: 126_000_000_000,
    languages: ["Amharic"],
    currency: "ETB",
    flag: "\u{1F1EA}\u{1F1F9}",
    funFacts: [
      "The only African country never colonized by a European power.",
      "Uses a calendar that is roughly 7 years behind the Gregorian calendar.",
      "Birthplace of coffee.",
    ],
    lat: 9.1,
    lng: 40.5,
  },
  {
    id: "morocco",
    name: "Morocco",
    capital: "Rabat",
    continent: "Africa",
    region: "Northern Africa",
    population: 37_100_000,
    area: 446_550,
    gdp: 134_000_000_000,
    languages: ["Arabic", "Berber"],
    currency: "MAD",
    flag: "\u{1F1F2}\u{1F1E6}",
    funFacts: [
      "Home to the oldest university in the world, the University of al-Qarawiyyin (859 AD).",
      "The blue city of Chefchaouen is one of the most photographed places in Africa.",
    ],
    lat: 31.8,
    lng: -7.1,
  },
  {
    id: "dr-congo",
    name: "DR Congo",
    capital: "Kinshasa",
    continent: "Africa",
    region: "Central Africa",
    population: 99_000_000,
    area: 2_344_858,
    gdp: 55_000_000_000,
    languages: ["French"],
    currency: "CDF",
    flag: "\u{1F1E8}\u{1F1E9}",
    funFacts: [
      "The Congo River is the deepest river in the world (230 m).",
      "Second-largest country in Africa by area.",
    ],
    lat: -4.0,
    lng: 21.8,
  },

  // ── Asia ───────────────────────────────────────────────────────
  {
    id: "india",
    name: "India",
    capital: "New Delhi",
    continent: "Asia",
    region: "Southern Asia",
    population: 1_428_600_000,
    area: 3_287_263,
    gdp: 3_730_000_000_000,
    languages: ["Hindi", "English"],
    currency: "INR",
    flag: "\u{1F1EE}\u{1F1F3}",
    funFacts: [
      "The most populous country in the world as of 2023.",
      "Has 22 officially recognized languages and hundreds more.",
      "Home to the Taj Mahal, one of the New Seven Wonders.",
    ],
    lat: 20.6,
    lng: 79.0,
  },
  {
    id: "china",
    name: "China",
    capital: "Beijing",
    continent: "Asia",
    region: "Eastern Asia",
    population: 1_412_600_000,
    area: 9_596_961,
    gdp: 17_960_000_000_000,
    languages: ["Mandarin"],
    currency: "CNY",
    flag: "\u{1F1E8}\u{1F1F3}",
    funFacts: [
      "The Great Wall of China stretches over 21,000 km.",
      "Invented paper, printing, gunpowder, and the compass.",
      "Has the world's largest high-speed rail network.",
    ],
    lat: 35.9,
    lng: 104.2,
  },
  {
    id: "japan",
    name: "Japan",
    capital: "Tokyo",
    continent: "Asia",
    region: "Eastern Asia",
    population: 125_700_000,
    area: 377_975,
    gdp: 4_230_000_000_000,
    languages: ["Japanese"],
    currency: "JPY",
    flag: "\u{1F1EF}\u{1F1F5}",
    funFacts: [
      "Made up of 6,852 islands.",
      "Has more than 1,500 earthquakes per year.",
      "Vending machines sell everything from hot soup to fresh eggs.",
    ],
    lat: 36.2,
    lng: 138.3,
  },
  {
    id: "south-korea",
    name: "South Korea",
    capital: "Seoul",
    continent: "Asia",
    region: "Eastern Asia",
    population: 51_700_000,
    area: 100_210,
    gdp: 1_670_000_000_000,
    languages: ["Korean"],
    currency: "KRW",
    flag: "\u{1F1F0}\u{1F1F7}",
    funFacts: [
      "Has the fastest average internet speed in the world.",
      "K-pop and Korean dramas are a global cultural phenomenon.",
    ],
    lat: 35.9,
    lng: 128.0,
  },
  {
    id: "indonesia",
    name: "Indonesia",
    capital: "Jakarta",
    continent: "Asia",
    region: "South-Eastern Asia",
    population: 275_500_000,
    area: 1_904_569,
    gdp: 1_320_000_000_000,
    languages: ["Indonesian"],
    currency: "IDR",
    flag: "\u{1F1EE}\u{1F1E9}",
    funFacts: [
      "The world's largest archipelago with over 17,000 islands.",
      "Home to the Komodo dragon, the world's largest living lizard.",
      "Has the world's largest Buddhist temple, Borobudur.",
    ],
    lat: -0.8,
    lng: 113.9,
  },
  {
    id: "saudi-arabia",
    name: "Saudi Arabia",
    capital: "Riyadh",
    continent: "Asia",
    region: "Western Asia",
    population: 35_900_000,
    area: 2_149_690,
    gdp: 1_110_000_000_000,
    languages: ["Arabic"],
    currency: "SAR",
    flag: "\u{1F1F8}\u{1F1E6}",
    funFacts: [
      "Home to Islam's two holiest cities, Mecca and Medina.",
      "Has no permanent rivers.",
      "The Rub' al Khali is the largest sand desert in the world.",
    ],
    lat: 23.9,
    lng: 45.1,
  },
  {
    id: "iran",
    name: "Iran",
    capital: "Tehran",
    continent: "Asia",
    region: "Western Asia",
    population: 87_900_000,
    area: 1_648_195,
    gdp: 388_000_000_000,
    languages: ["Persian"],
    currency: "IRR",
    flag: "\u{1F1EE}\u{1F1F7}",
    funFacts: [
      "One of the oldest civilizations in the world, dating back to 3200 BC.",
      "Home to the Dasht-e Kavir, one of the world's largest salt deserts.",
    ],
    lat: 32.4,
    lng: 53.7,
  },
  {
    id: "iraq",
    name: "Iraq",
    capital: "Baghdad",
    continent: "Asia",
    region: "Western Asia",
    population: 41_200_000,
    area: 438_317,
    gdp: 264_000_000_000,
    languages: ["Arabic", "Kurdish"],
    currency: "IQD",
    flag: "\u{1F1EE}\u{1F1F6}",
    funFacts: [
      "Ancient Mesopotamia, between the Tigris and Euphrates, is considered the cradle of civilization.",
      "Home to the ancient city of Babylon.",
    ],
    lat: 33.2,
    lng: 43.7,
  },
  {
    id: "thailand",
    name: "Thailand",
    capital: "Bangkok",
    continent: "Asia",
    region: "South-Eastern Asia",
    population: 71_800_000,
    area: 513_120,
    gdp: 535_000_000_000,
    languages: ["Thai"],
    currency: "THB",
    flag: "\u{1F1F9}\u{1F1ED}",
    funFacts: [
      "The only Southeast Asian country never colonized by a European power.",
      "Bangkok's full ceremonial name has 169 characters.",
    ],
    lat: 15.9,
    lng: 100.9,
  },
  {
    id: "vietnam",
    name: "Vietnam",
    capital: "Hanoi",
    continent: "Asia",
    region: "South-Eastern Asia",
    population: 98_200_000,
    area: 331_212,
    gdp: 409_000_000_000,
    languages: ["Vietnamese"],
    currency: "VND",
    flag: "\u{1F1FB}\u{1F1F3}",
    funFacts: [
      "The world's largest exporter of cashew nuts and black pepper.",
      "Ha Long Bay has over 1,600 limestone islands.",
    ],
    lat: 14.1,
    lng: 108.3,
  },
  {
    id: "philippines",
    name: "Philippines",
    capital: "Manila",
    continent: "Asia",
    region: "South-Eastern Asia",
    population: 115_600_000,
    area: 300_000,
    gdp: 404_000_000_000,
    languages: ["Filipino", "English"],
    currency: "PHP",
    flag: "\u{1F1F5}\u{1F1ED}",
    funFacts: [
      "Made up of 7,641 islands.",
      "Texting capital of the world — Filipinos send the most text messages per capita.",
    ],
    lat: 12.9,
    lng: 121.8,
  },
  {
    id: "pakistan",
    name: "Pakistan",
    capital: "Islamabad",
    continent: "Asia",
    region: "Southern Asia",
    population: 231_400_000,
    area: 881_913,
    gdp: 376_000_000_000,
    languages: ["Urdu", "English"],
    currency: "PKR",
    flag: "\u{1F1F5}\u{1F1F0}",
    funFacts: [
      "Home to K2, the second-highest mountain in the world.",
      "The Indus Valley Civilization (3300 BC) was one of the earliest urban cultures.",
    ],
    lat: 30.4,
    lng: 69.3,
  },
  {
    id: "bangladesh",
    name: "Bangladesh",
    capital: "Dhaka",
    continent: "Asia",
    region: "Southern Asia",
    population: 169_400_000,
    area: 147_570,
    gdp: 460_000_000_000,
    languages: ["Bengali"],
    currency: "BDT",
    flag: "\u{1F1E7}\u{1F1E9}",
    funFacts: [
      "The Sundarbans is the largest mangrove forest in the world.",
      "One of the most densely populated countries on Earth.",
    ],
    lat: 23.7,
    lng: 90.4,
  },
  {
    id: "israel",
    name: "Israel",
    capital: "Jerusalem",
    continent: "Asia",
    region: "Western Asia",
    population: 9_700_000,
    area: 22_072,
    gdp: 525_000_000_000,
    languages: ["Hebrew", "Arabic"],
    currency: "ILS",
    flag: "\u{1F1EE}\u{1F1F1}",
    funFacts: [
      "The Dead Sea is the lowest point on Earth's surface.",
      "Has more startups per capita than any other nation.",
    ],
    lat: 31.0,
    lng: 34.9,
  },
  {
    id: "uae",
    name: "United Arab Emirates",
    capital: "Abu Dhabi",
    continent: "Asia",
    region: "Western Asia",
    population: 9_400_000,
    area: 83_600,
    gdp: 507_000_000_000,
    languages: ["Arabic"],
    currency: "AED",
    flag: "\u{1F1E6}\u{1F1EA}",
    funFacts: [
      "The Burj Khalifa is the tallest building in the world at 828 m.",
      "Dubai's Palm Jumeirah is visible from space.",
    ],
    lat: 23.4,
    lng: 53.8,
  },
  {
    id: "singapore",
    name: "Singapore",
    capital: "Singapore",
    continent: "Asia",
    region: "South-Eastern Asia",
    population: 5_900_000,
    area: 733,
    gdp: 397_000_000_000,
    languages: ["English", "Malay", "Mandarin", "Tamil"],
    currency: "SGD",
    flag: "\u{1F1F8}\u{1F1EC}",
    funFacts: [
      "One of only three surviving city-states in the world.",
      "Chewing gum is banned (with medical exceptions).",
    ],
    lat: 1.4,
    lng: 103.8,
  },
  {
    id: "malaysia",
    name: "Malaysia",
    capital: "Kuala Lumpur",
    continent: "Asia",
    region: "South-Eastern Asia",
    population: 33_900_000,
    area: 330_803,
    gdp: 407_000_000_000,
    languages: ["Malay"],
    currency: "MYR",
    flag: "\u{1F1F2}\u{1F1FE}",
    funFacts: [
      "The Petronas Twin Towers were the tallest buildings in the world from 1998 to 2004.",
      "Home to one of the oldest tropical rainforests in the world (130 million years).",
    ],
    lat: 4.2,
    lng: 101.0,
  },

  // ── Oceania ────────────────────────────────────────────────────
  {
    id: "australia",
    name: "Australia",
    capital: "Canberra",
    continent: "Oceania",
    region: "Australia and New Zealand",
    population: 26_000_000,
    area: 7_692_024,
    gdp: 1_680_000_000_000,
    languages: ["English"],
    currency: "AUD",
    flag: "\u{1F1E6}\u{1F1FA}",
    funFacts: [
      "The only country that is also a continent.",
      "Home to 21 of the world's 25 most venomous snakes.",
      "The Great Barrier Reef is the largest living structure on Earth.",
    ],
    lat: -25.3,
    lng: 133.8,
  },
  {
    id: "new-zealand",
    name: "New Zealand",
    capital: "Wellington",
    continent: "Oceania",
    region: "Australia and New Zealand",
    population: 5_100_000,
    area: 268_838,
    gdp: 247_000_000_000,
    languages: ["English", "Maori"],
    currency: "NZD",
    flag: "\u{1F1F3}\u{1F1FF}",
    funFacts: [
      "First country to give women the right to vote (1893).",
      "Has more sheep than people — about 6 sheep per person.",
      "No native land mammals (except bats).",
    ],
    lat: -40.9,
    lng: 174.9,
  },
];

export const countryMap = new Map(countries.map((c) => [c.id, c]));

export function getCountry(id: string): Country | undefined {
  return countryMap.get(id);
}

export function countriesByContinent(continent: Continent): Country[] {
  return countries.filter((c) => c.continent === continent);
}

export const continents: Continent[] = [
  "Africa",
  "Asia",
  "Europe",
  "North America",
  "South America",
  "Oceania",
];

/** Major countries for easy quiz difficulty */
export const easyCountryIds = new Set([
  "usa",
  "canada",
  "mexico",
  "brazil",
  "uk",
  "france",
  "germany",
  "spain",
  "italy",
  "russia",
  "india",
  "china",
  "japan",
  "australia",
  "egypt",
  "south-africa",
  "nigeria",
  "argentina",
  "south-korea",
  "indonesia",
]);

export function formatPopulation(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(2)}B`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K`;
  return String(n);
}

export function formatArea(n: number): string {
  return n.toLocaleString() + " km²";
}

export function formatGdp(n: number): string {
  if (n >= 1_000_000_000_000) return `$${(n / 1_000_000_000_000).toFixed(2)}T`;
  if (n >= 1_000_000_000) return `$${(n / 1_000_000_000).toFixed(0)}B`;
  return `$${(n / 1_000_000).toFixed(0)}M`;
}

export function populationDensity(c: Country): number {
  return c.population / c.area;
}

export function gdpPerCapita(c: Country): number {
  return c.gdp / c.population;
}
